''' LOOPS IN PYTHON
RANGE FUNCTION: used to generate a sequence of numbers. It can take one, two, or three arguments:
- range(stop): generates numbers from 0 to stop-1.
- range(start, stop): generates numbers from start to stop-1.
- range(start, stop, step): generates numbers from start to stop-1, incrementing by step.
Range function is commonly used in for loops to iterate a specific number of times.

NOTE: In Python 3, the range() function returns a range object, which is an iterable that generates numbers on demand.
To print the numbers generated by the range function, you can convert the range object to a list using the list() function.
    print(list(range(5))) # prints [0, 1, 2, 3, 4]

'''

# Range function examples
range(5) # generates numbers from 0 to 4
print(range(5)) # In Python 3, prints the range object, that is "range(0, 5)", not the numbers
print(list(range(5))) # converts the range object to a list and prints it

range(2, 5) # generates numbers from 2 to 4
print(list(range(2, 5))) # prints [2, 3, 4]

range(0, 10, 2) # generates numbers from 0 to 9, incrementing by 2 (0, 2, 4, 6, 8)
print(list(range(0, 10, 2))) # prints [0, 2, 4, 6, 8]


'''
KIND OF LOOPS
1. For Loop - used for iterating over a sequence (like a list, tuple, dictionary, set, or string) or other iterable objects.
    SYNTAX:
    for variable in iterable:
        # code block to be executed
2. While Loop - used to execute a block of code as long as a specified condition is true.
    SYNTAX:
    while condition:
        # code block to be executed


WHEN TO USE EACH LOOP
FOR LOOPS: Use for loops when you know the number of iterations in advance or when iterating over a sequence.
    - are like helpers that made us repeat tasks in order
WHILE LOOPS: Use while loops when the number of iterations is not known in advance and depends on a condition.
    - are like detectives that kept doing something as long as a rule is true
'''

# EXAMPLES: NUMBER SEQUENCE GENERATION USING LOOPS
# For loop example
for i in range(5):
    print(i) # prints numbers from 0 to 4

# While loop example
count = 0
while count < 5:
    print(count) # prints numbers from 0 to 4
    count += 1 # increments count by 1 in each iteration

# EXAMPLES: LIST SEQUENCE USING LOOPS
# For loop example
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit) # prints each fruit in the list

# While loop example
fruits = ["apple", "banana", "cherry"]
ind = 0 # as in index
while ind < len(fruits):
    print(fruits[ind]) # prints each fruit in the list
    ind += 1 # increments index by 1 in each iteration